### ISSUE TITLE
PostgreSQL Binding fails

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/fluent-postgresql#24]
```
⚠️ [PostgreSQLDiagnosticResponse.exec_bind_message: ERROR: bind message supplies 2 parameters, but prepared statement "" requires 1] [Possible causes: bind message supplies 2 parameters, but prepared statement "" requires 1]
```
When executing 
```swift
let stuff = Allergy.query(on: req).filter(\Allergy.id, in: allergyIds).all().map(to: [Allergy].self, { a in
    print(a)
    return a
}).catchMap({ (err) in
    print(err)
    return []
}).catch({ (err) in
    print(err)
})
```
This error is thrown to an encoding error it seems on something. I am using UUID's as id's for my tables. I have tested this in a clean project as well. 

**Update:** It appears that the same thing happens when using an or group as well. I'm thinking that the UUID encoding is failing.
```swift
let items = Allergy.query(on: req).group(.or, closure: { builder in
    for id in allergyIds {
       builder.filter(\Allergy.id == id)
     }
}).count().do({ (amount) in
    print("Count: \(amount)")
}).catch({ (err) in
    print(err)
})
````

**Comment by tanner0101** [comment]
@anthonycastelli I added a test case for this (see commit above) and it seems to be working properly on `nio` branch. Let me know if that looks good, thanks :)

**Comment by anthonycastelli** [comment]
That looks right to me. However, I am using a UUID vs a regular Int so not sure if the UUID was causing problems. Will test out the bio branch at some point though
