### ISSUE TITLE
withPooledConnection throws "nil database identifier"

### ISSUE THREAD

**Issue by alxstu** [vapor/fluent-postgresql#3]
Example: 
```
return request.withPooledConnection(to: .psql, closure: { (db) -> Future<[User]> in
            return User.query(on: db).all()
    })
```

(or any other query on: db) throws "nil database identifier" in DatabaseConnection

Changing the Project to mysql works as expected.

**Comment by tanner0101** [comment]
@alxstu try setting `User.defaultDatabase = .psql`. 

Either way, we should have a better error message there.

**Comment by alxstu** [comment]
this: https://github.com/vapor/database-kit/commit/408b1d91e8abb7a96c6549ee4a9ef9520047a6b7 fixed the problem!
