### ISSUE TITLE
Not working with Int64 array?

### ISSUE THREAD

**Issue by lephyrius** [vapor/fluent-postgresql#35]
I have a model that looks like this:
```swift
struct Game: PostgreSQLModel, Codable {
var id: Int?
var tags: [Int64]?
}
```

I want to store an array of int64 tags in the model the case where there is multiple ints in the array works but also if the array is nil (empty) works.
But the case where it only contains a single value gives me:
`DecodingError.typeMismatch: Value of type 'Int64' required for key ''.`
But only on linux.
Using swift 4.1 + PostgreSQL 10 .

**Comment by tanner0101** [comment]
This should work now (see the added test). Thanks!
