### ISSUE TITLE
What's the package line?

### ISSUE THREAD

**Issue by grosch** [vapor/fluent-postgresql#36]
I tried putting this in my Package.swift:

> .package(url: "https://github.com/vapor/fluent-postgresql.git", .upToNextMajor(from: "1.0.0-rc"))

and 'vapor -y xcode' just spins.

**Comment by twof** [comment]
It's going to be either `.upToNextMajor()` or `from:` but not both. The one most people are using is 

`.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc"))`

SPM is pretty bad about give you the info you need to debug your package, so I'd suggest `vapor xcode --verbose -y` to get a little more info.

**Comment by grosch** [comment]
I switched it to the line you showed and then ran with verbose.  It ran through these in just a couple seconds, but then just stopped with no more output:

% vapor xcode --verbose -y
Generating Xcode Project ...
Updating https://github.com/vapor/fluent-postgresql.git
Updating https://github.com/vapor/vapor.git
Updating https://github.com/vapor/fluent-provider.git
Updating https://github.com/vapor/routing.git
Updating https://github.com/vapor/multipart.git
Updating https://github.com/vapor/node.git
Updating https://github.com/vapor/bcrypt.git
Updating https://github.com/vapor/core.git
Updating https://github.com/vapor/crypto.git
Updating https://github.com/vapor/engine.git
Updating https://github.com/vapor/console.git
Updating https://github.com/vapor/json.git
Updating https://github.com/vapor/random.git
Updating https://github.com/vapor/bits.git
Updating https://github.com/vapor/debugging.git
Updating https://github.com/vapor/ctls.git
Updating https://github.com/vapor/sockets.git
Updating https://github.com/vapor/tls.git
Updating https://github.com/vapor/fluent.git
Updating https://github.com/vapor/sqlite.git
Updating https://github.com/vapor/postgresql.git
Updating https://github.com/vapor/async.git

**Comment by twof** [comment]
Can you share your entire `Package.swift` and whether you're trying to use Vapor 2 or Vapor 3?

**Comment by MrMage** [comment]
I've had the same experience when my `Package.swift` specified different branches/versions for transitive dependencies than what was specified by other dependencies. Make sure that all your dependencies and your `Package.swift` specify the same version/branch for all packages, and if that doesn't help, please post your `Package.swift` as mentioned by @twof.

**Comment by grosch** [comment]
Apparently I was using Vapor 2 and this is for Vapor 3.  I fixed that and now I'm good.
