### ISSUE TITLE
Add support for `timestamp with time zone` PostgreSQL column type

### ISSUE THREAD

**Issue by andrewtheis** [vapor/fluent-postgresql#40]
The `timestamp with time zone` PostgreSQL column type is supported by the existing PostgreSQLProvider. Support for this column type should be added before the final Vapor 3 release.

**Comment by andrewtheis** [comment]
After some digging, it looks like PostgreSQL driver doesn't actually parse timezone with time stamp any differently:

https://github.com/vapor-community/postgresql/blob/cfbfa12c148fd2b44e6777d4ed2f57ca597e06e7/Sources/PostgreSQL/Bind/BinaryUtils.swift#L337
https://github.com/vapor-community/postgresql/blob/cfbfa12c148fd2b44e6777d4ed2f57ca597e06e7/Sources/PostgreSQL/Bind/Bind%2BNode.swift#L93

I'm going to try converting the column type to see if it makes any difference in the date instantiated.

**Comment by andrewtheis** [comment]
Seems converting the columns from `with timezone` to `without timezone` drops that data but doesn't change the value. This works as a workaround, but might be a good idea to support that column type and just drop that information as well when creating  the `Date`.

**Comment by tanner0101** [comment]
The `TIMESTAMPTZ` and `TIMETZ` types have been added in #67
