### ISSUE TITLE
PostgreSQLModel should use Int64 (instead of int)

### ISSUE THREAD

**Issue by brntphish** [vapor/fluent-postgresql#47]
When utilizing PostgreSQLModel in Vapor 3 the int declared as the id is actually stored as a bigint in postgres according to pgadmin. However you cannot declare id as an Int64/bigint 

```
final class myClass: Codable {
  var id: Int?
  var name: String
  var createdAt: Date?
  var updatedAt: Date?
  
  // MARK: Init
  init(name: String) {
    self.name = name
  }
  
  init(id: Int, name: String) {
    self.id = id
    self.name = name
  }
}
```

![screen shot 2018-05-04 at 6 00 26 pm](https://user-images.githubusercontent.com/20200349/39656405-24fc0eb8-4fc5-11e8-9feb-5793db1255e0.png)

if already being stored as a bigint in pg, I purpose just changing the int? to an Int64? to prevent breaking any bigint keys that already exist.

**Comment by MrMage** [comment]
If I recall, I also had problems using `Int64` IDs, but can’t remember the error message.

I also remember changing those primary keys to `BIGINT` automatically for 8-byte wide integers (which `Int` is on 64-bit systems). So I’d say at least the `BIGINT` part is working as expected; use `Int32` if you don’t want `BIGINT`s.

**Comment by brntphish** [comment]
@tanner0101 
if you do this "var id: Int64?" when using a postgreSQL model, it tells you it does not conform and attempts to re-add an id stub. even though they are being stored in pg as int64/bigint

**Comment by 0xTim** [comment]
@brntphish does it work if you manually conform to `Model` though?

**Comment by tanner0101** [comment]
This should work if you use `Model` directly (not `PostgreSQLModel`). Closing this since the default should not be a problem on any platform that Vapor supports (they are all 64-bit).
