### ISSUE TITLE
query.sum() should be generic

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/fluent-postgresql#50]
Trying to get sum of money movements by calling
```swift
MoneyMovement.query(on: conn).sum(\MoneyMovement.quantity).flatMap { sumOfIncomes -> EventLoopFuture<Int64> in
    //somehow `sumOfIncomes` is Double, that's strange because `MoneyMovement.quantity` is Int64
}
```
but getting error
```swift
[ ERROR ] PostgreSQLError.binaryFloatingPoint: Could not decode Double from binary data type: NUMERIC.
```

<img width="558" alt="2018-05-08 21 49 56" src="https://user-images.githubusercontent.com/1272610/39773646-c59b2c18-5309-11e8-96a4-801ef405a945.png">

**Comment by MihaelIsaev** [comment]
Tried to change `MoneyMovement.quantity` column type to `double precision` in the database and variable type to `Double` in the Model, but getting the same error.. looks like `.sum()` is completely broken

**Comment by MrMage** [comment]
Related: https://github.com/vapor/fluent/issues/450#issuecomment-382047483

Also, I think this (at least partially) affects Fluent itself, not Postgres specifically.

**Comment by tanner0101** [comment]
As of 1.0.0, `sum(...)` will be the same type as the field it is called on.
