### ISSUE TITLE
OID is Uint32 not int32

### ISSUE THREAD

**Issue by mura-admin** [vapor/fluent-postgresql#51]
Should be an easy fix. Will break when it encounters > int32max

**Comment by mura-admin** [comment]
Submitted a pull request: https://github.com/vapor/fluent-postgresql/pull/52

**Comment by AxelCB** [comment]
@tanner0101 Shouldn't this issue be closed due to the latest release of vapor/postgresql including https://github.com/vapor/postgresql/pull/58 ?

**Comment by mura-admin** [comment]
Yes looks like this has been fixed in https://github.com/vapor/fluent-postgresql/commit/8324bf0fc1437701f8963fb340c199c66079c90e
