### ISSUE TITLE
Identity columns should only be used on PostgreSQL 10

### ISSUE THREAD

**Issue by vzsg** [vapor/fluent-postgresql#6]
On earlier versions, the current [implementation](https://github.com/vapor/fluent-postgresql/blob/ef5c819f9c0a2749c46e80d455bb766241f945b3/Sources/FluentPostgreSQL/PostgreSQLDatabase%2BSchemaSupporting.swift#L19-L23) will throw a syntax error.

Either fluent-postgresql should detect which PG version it is connected to, and use that information while generating the column type, or the Identity feature should be opt-in.

**Comment by tanner0101** [comment]
`FluentPostgreSQLProvider(enableIdentityColumns: false)`
