### ISSUE TITLE
Optionals have not-null constraint in DB

### ISSUE THREAD

**Issue by xaverlohmueller** [vapor/fluent-postgresql#61]
I'm having a model that looks like this:
```
struct Customer: PostgreSQLModel {
    var id: Int?

    var name: String
    var pushId: String?
    var type: String
}
extension Customer: Migration {}
```

Now, when I'm trying to create a customer:

```
POST /api/customer HTTP/1.1
{
	"name": "Xav",
	"type": "iOS"
}
```
I'm getting an error: `ERROR: null value in column \"pushId\" violates not-null constraint`.

Looking in the `psql` database, I found that fluent generated the table with a `not null constraint`:
```
 Column |  Type  | Collation | Nullable |             Default              
--------+--------+-----------+----------+----------------------------------
 id     | bigint |           | not null | generated by default as identity
 name   | text   |           | not null | 
 pushId | text   |           | not null | 
 type   | text   |           | not null | 
```

Is this the intended behavior of Optionals with `fluent-postgresql`? If so, is there some documentation how to generate a nullable field?

**Comment by tanner0101** [comment]
@xaverlohmueller no, that must have been a bug. I just checked and columns with optional type (i.e., `String?`) don't have `NOT NULL` appended to the `CREATE TABLE` query. Let me know if this issue is also resolved on your end. Thanks!

**Comment by xaverlohmueller** [comment]
Sure, I'll check with the new PostgreSQL package that was released today/yesterday :+1:

**Comment by xaverlohmueller** [comment]
Sorry I didn't get to check this earlier, but it works like a charm now 👍! Thanks!
