### ISSUE TITLE
Upsert support

### ISSUE THREAD

**Issue by broadwaylamb** [vapor/fluent-postgresql#64]
Can we add an UPSERT support? PostgreSQL has the [ON CONFLICT](https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT) clause for this purpose.

I could try to implement this.

**Comment by tanner0101** [comment]
This should be possible once the latest Fluent updates land. Keep an eye on https://github.com/vapor/fluent/pull/482
