### ISSUE TITLE
Array encoding to JSONB

### ISSUE THREAD

**Issue by hjuraev** [vapor/fluent-postgresql#73]
var participants: [Participant] = []

this property converted to single JSONB object while migration created as JSONB[] column

[ ERROR ] ⚠️ [PostgreSQLError.server.error.transformAssignedExpr: column "participants" is of type jsonb[] but expression is of type jsonb] [Suggested fixes: You will need to rewrite or cast the expression.] (RouterController.swift:976)

**Comment by tanner0101** [comment]
See #35. A test has been added for this and is working properly. This is likely related to a bug that has been fixed. Run `swift package update` and let me know if you still see the issue, thanks!
