### ISSUE TITLE
Crash on ubuntu 16.04 [vapor 3 beta]

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/fluent-postgresql#8]
I'm trying to run Vapor 3 app on Unubtu 16.04 with Swift 4.1
<img width="1036" alt="2018-02-02 1 35 49" src="https://user-images.githubusercontent.com/1272610/35704798-0e6c08fe-07ba-11e8-93dc-5675afa24b2a.png">

Standart todo example with SQLite works, but with Postgres it fails.

> @tanner0101 : oh, that looks like we're generating invalid SQL

**Comment by tanner0101** [comment]
See #6
