### ISSUE TITLE
500 response when no model with id is found

### ISSUE THREAD

**Issue by addisonwebb** [vapor/fluent-postgresql#84]
This is a similar bug to https://github.com/vapor/fluent/issues/440. When a request is made for an object and it is not found a 500 error is returned instead of a 404.

**Comment by 0xTim** [comment]
There's a PR up to fix this in Vapor

**Comment by addisonwebb** [comment]
@0xTim awesome. Can you link that issue here?

**Comment by addisonwebb** [comment]
Thanks @0xTim. Closing this as a duplicate.
