### ISSUE TITLE
[Beta] Xcode crash on `PostgreSQLDatabaseConfig`

### ISSUE THREAD

**Issue by bensyverson** [vapor/fluent-postgresql#9]
## Summary
Calling `PostgreSQLDatabaseConfig(hostname: port: username: database: password: )` on a database/user that doesn't require a password results in an Xcode crash, probably at the Swift compiler level.

## Details
- Using Xcode 9.2 (13772) and Vapor 3
- And given a new database, initialized with:

```
$ createdb miiine
$ create user mine
$ psql miiine
miiine=# grant all privileges on database miiine to miiine;
miiine=# alter user miiine with encrypted password 'beyonceknowles';
```

…I can successfully connect using: `let psqlDatabaseConfig = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "miiine")`. No password is required, given that `psql -U miiine` does connect.

…However, if I (incorrectly?) try to pass in the database name and user password:
`let psqlDatabaseConfig = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "miiine", database: "miiine", password: "beyonceknowles")`

…I get a hard crash.

## Results
First, `Run` crashes (Illegal instruction)
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

External Modification Warnings:
Debugger attached to process.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	0x000000010129faf0 specialized _assertionFailure(_:_:file:line:flags:) + 144
1   libswiftCore.dylib            	0x000000010114f8d2 swift_errorInMain + 322
2   Run                           	0x0000000100002390 main + 1120 (main.swift:6)
3   libdyld.dylib                 	0x00007fff6d373015 start + 1
```

Then Xcode comes down:
```
Crashed Thread:        27  <DBGLLDBSessionThread (pid=62812)>

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000d8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]
…
Thread 27 Crashed:: <DBGLLDBSessionThread (pid=62812)>
0   libsystem_pthread.dylib       	0x00007fff6d67d4a3 _pthread_mutex_lock_slow + 79
1   com.apple.CoreFoundation      	0x00007fff44e42013 CFRunLoopPerformBlock + 179
2   com.apple.dt.DVTFoundation    	0x0000000101afb78d _DVTAsyncPerformBlockOnMainRunLoop + 192
3   com.apple.dt.DVTFoundation    	0x0000000101afb6a0 DVTAsyncPerformBlock + 83
4   com.apple.dt.dbg.DebuggerLLDB 	0x000000010ec4fb5a -[DBGLLDBProcess _updateThreadStateAndStopReason:controlState:] + 1242
```

## Steps to reproduce
- [Download the example project](https://gitlab.com/bensyverson/miiine/tree/c284433d8d4af6803bd7074c0f5e5b7f41db54f4)
- Create a new database and set the name in Line 18 of `/App/Setup/Configure.swift`
- Run `Run` to ensure that the password-less version is booting properly
- Then change line 18:
    - from: `let psqlDatabaseConfig = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "miiine")`
    - to: `let psqlDatabaseConfig = PostgreSQLDatabaseConfig(hostname: "localhost", port: 5432, username: "miiine", database: "miiine", password: "beyonceknowles")`
- Now run `Run` again, and it should crash.

**Comment by 0xTim** [comment]
@bensyverson this is the probably the known bug in Xcode where a top-level error in main.swift that isn't handled will take down Xcode...great design there!

If you run it from the command line you should see the actual error if it is that.

**Comment by bensyverson** [comment]
Ah, makes sense! Shouldn't the Vapor Error middleware handle it though?

**Comment by 0xTim** [comment]
Depends where the error occurs - on startup there is no catch in the chain to catch the error and it can happen if the error is thrown outside the middleware chain as well.

Hopefully a future version of Xcode will fix this, I haven't actually seen it on 9.3

**Comment by bensyverson** [comment]
That explains it! Thanks—this can probably be closed then.

**Comment by pardel** [comment]
This now happens in both Xcode 9.4.1 and 10.0b6 only when no password is required for the user.

**Comment by H-Ghadirian** [comment]
Same error 
Xcode Version 10.1 (10B61)
Vapor 3

**Comment by 0xTim** [comment]
@H-Ghadirian what's the full error message?

**Comment by H-Ghadirian** [comment]
@0xTim 
Fatal error: Error raised at top level: ⚠️ PostgreSQL Error: No password is required
- id: PostgreSQL.PostgreSQLError.trust

**Comment by 0xTim** [comment]
How are you configuring the database config? Are you on the latest code?
