### ISSUE TITLE
Cannot convert value of type '(_) - when use query inside compactMap

### ISSUE THREAD

**Issue by ahmedraad** [vapor/fluent-postgresql#98]
I've this method here, it shows an error 

```Swift
func all(_ req: Request) throws -> Future<[Journey.Public]> {
        return Journey.query(on: req)
            .join(\User.id, to: \Journey.userID)
            .alsoDecode(User.self)
            .all()
            .flatMap(to: [Journey.Public].self, { data in

                return try data.compactMap({ args in

                    let (journey, user) = args

                    return try user.cars.query(on: req).first().map(to: Journey.Public.self, { car in
                        return Journey.Public(journey, u: User.DisplayUser(user, car: car, rating: "0"))
                    })
                    
                }).flatten(on: req)
         })
 }
```

<img width="1326" alt="screen shot 2018-10-13 at 8 39 52 pm" src="https://user-images.githubusercontent.com/17860965/46908199-3636c280-cf28-11e8-991f-be77e36dc4fc.png">

**`Cannot convert value of type '(_) throws -> EventLoopFuture<Void>' to expected argument type '([(Journey, User)]) throws -> EventLoopFuture<_>'`**

So the guys on discord gave me a bunch of solutions, but non of them work. 
btw `Journey.Public`, `DisplayUser` structs are confirmed to Content

`Vapor Toolbox: 3.1.10`
`Vapor 3.1.0`
`FluentPostgreSQL 1.0.0`

**Comment by tanner0101** [comment]
Try adding explicit return types to the closures to aid the compiler in generating a better error message:

```swift
{ () -> Foo in
    return someFoo
}
```

**Comment by ahmedraad** [comment]
it works now by adding return type `-> EventLoopFuture<Journey.Public>` to `data.compactMap`

@tanner0101 thanks!
